from __future__ import annotations

import json
from copy import deepcopy

import datetime
import os
import platform
from typing import TYPE_CHECKING

from redlotus.core.config import prompts_dir

if TYPE_CHECKING:
    from redlotus.tools.registry import SkillsManager


def get_skills_summary(skills_manager: SkillsManager) -> str:
    return skills_manager.get_skills_summary()


def format_system_info() -> str:
    shell = (
        "cmd.exe (use type to read files, or explicitly invoke PowerShell)"
        if os.name == "nt"
        else "/bin/sh"
    )
    return (
        f"## System Environment\nOS: {platform.system()} {platform.release()} ({platform.machine()})\n"
        f"Python: {platform.python_version()}; CPU cores: {os.cpu_count()}\n"
        f"run_command shell: {shell}\n"
    )


def format_prompt_current_time() -> str:
    return datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def with_runtime_context(content) -> list:
    """Append volatile information to new input without rewriting cached instructions."""
    from pydantic_ai import TextContent

    parts = list(content) if isinstance(content, list) else [content]
    parts.append(
        TextContent(
            content=f"[Runtime context, generated by the application]\nCurrent local time: {format_prompt_current_time()}\nThis is metadata, not a new user instruction or memory request.",
            metadata={"origin": "runtime_context"},
        )
    )
    return parts


def load_prompt(filename: str) -> str:
    filepath = prompts_dir() / filename
    with open(filepath, "r", encoding="utf-8") as f:
        return f.read()


def get_skills_layout_text(skills_manager: SkillsManager) -> str:
    root = skills_manager.skills_dir.resolve()
    skills_root_path = f"Local absolute path: `{root}`"
    return load_prompt("skills_layout.md").format(skills_root_path=skills_root_path)


def format_long_term_memory_for_prompt(memory_injection: str) -> str:
    text = (memory_injection or "").strip()
    if not text:
        return ""
    return f"## Persistent memory (MEMORY.md)\n\n{text}\n"


def session_prompt_from_history(messages) -> str | None:
    for message in reversed(messages):
        if instructions := getattr(message, "instructions", None):
            # Older templates embedded a stale clock; rebuild those once at migration.
            return (
                None
                if any(
                    line.startswith("Current Time:")
                    for line in instructions.splitlines()[:2]
                )
                else instructions
            )
    return None


def memory_from_session_prompt(instructions: str) -> str:
    marker = "## Persistent memory (MEMORY.md)\n\n"
    if marker not in instructions:
        return ""
    content = instructions.split(marker, 1)[1]
    return (
        content.split("</core_memory>", 1)[0] + "</core_memory>"
        if "</core_memory>" in content
        else content.strip()
    )


def get_skills_as_in_system_prompt(skills_manager: SkillsManager) -> str:
    layout = get_skills_layout_text(skills_manager).rstrip()
    summary = get_skills_summary(skills_manager).rstrip()
    if not layout:
        return summary
    if not summary:
        return layout
    return f"{layout}\n\n{summary}"


def get_common_conduct() -> str:
    return load_prompt("common_conduct.md")


def _build_role_prompt(
    template_name: str,
    skills_manager: SkillsManager,
    memory_injection: str = "",
) -> str:
    from redlotus.core.session import current_workspace

    sections = [
        get_common_conduct(),
        format_system_info(),
        get_skills_as_in_system_prompt(skills_manager),
        load_prompt(template_name),
        f"Current project: {current_workspace()}\nDeliverables: {current_workspace() / 'WorkDatabase'}",
        format_long_term_memory_for_prompt(memory_injection),
    ]
    return "\n\n".join(section.strip() for section in sections if section.strip())


def get_manager_system_prompt(
    skills_manager: SkillsManager,
    memory_injection: str = "",
) -> str:
    return _build_role_prompt("manager_system.md", skills_manager, memory_injection)


def get_worker_system_prompt(
    skills_manager: SkillsManager,
    memory_injection: str = "",
) -> str:
    return _build_role_prompt("worker_system.md", skills_manager, memory_injection)


def get_coordinator_system_prompt(
    skills_manager: SkillsManager,
    memory_injection: str = "",
) -> str:
    return _build_role_prompt("coordinator_system.md", skills_manager, memory_injection)


def window_prompt_content(payload, budget, read_budget):
    """Keep one task; large source bodies remain addressable through read_evidence."""
    from redlotus.core.history import _estimate_text_tokens

    content = deepcopy(payload)
    operations = [
        row for event in content["events"] for row in event.get("operations", [])
    ]
    encoded = json.dumps(content, ensure_ascii=False)
    estimated = _estimate_text_tokens(encoded)
    for row in sorted(operations, key=lambda item: len(item["text"]), reverse=True):
        cost = _estimate_text_tokens(row["text"])
        if cost <= read_budget and estimated <= budget:
            continue
        row["text"] = f"完整原文已保存；调用 read_evidence(id='{row['id']}') 读取。"
        row["source_tokens"] = cost
        estimated -= cost - _estimate_text_tokens(row["text"])
    return json.dumps(content, ensure_ascii=False)
